version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.local
    working_dir: /app
    depends_on:
      - mysql_db
    env_file:
      - ./server/.env.development.local
    develop: 
      watch: 
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  mysql_db:
    container_name: mysql_db
    image: mysql
    ports:
      - "3307:3307"
    env_file:
      - ./server/.env.development.local
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    restart: always
    develop:
      watch:
        - action: sync
          path: ./client/app
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3040:80"